import AppKit

/// Watches the system pasteboard and records new copies into the history.
final class ClipboardManager {
    private let store: HistoryStore
    private var timer: Timer?
    private var lastChangeCount: Int

    // Content marked with these types (password managers, transient copies) is not stored.
    private let skipTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    init(store: HistoryStore) {
        self.store = store
        lastChangeCount = NSPasteboard.general.changeCount
    }

    func start() {
        let timer = Timer(timeInterval: 0.4, repeats: true) { [weak self] _ in self?.poll() }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    private func poll() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount

        let types = pb.types ?? []
        if types.contains(where: { skipTypes.contains($0.rawValue) }) { return }

        let source = NSWorkspace.shared.frontmostApplication?.localizedName

        if let string = pb.string(forType: .string),
           !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            store.addText(string, source: source)
        } else if let data = imageData(from: pb) {
            store.addImage(data, source: source)
        }
    }

    private func imageData(from pb: NSPasteboard) -> Data? {
        if let png = pb.data(forType: .png) { return png }
        if let tiff = pb.data(forType: .tiff), let rep = NSBitmapImageRep(data: tiff) {
            return rep.representation(using: .png, properties: [:])
        }
        if let img = NSImage(pasteboard: pb), let tiff = img.tiffRepresentation,
           let rep = NSBitmapImageRep(data: tiff) {
            return rep.representation(using: .png, properties: [:])
        }
        return nil
    }

    /// Puts an item onto the system pasteboard (used right before simulating ⌘V).
    func copyToPasteboard(_ item: ClipItem) {
        let pb = NSPasteboard.general
        pb.clearContents()
        switch item.kind {
        case .text:
            pb.setString(item.text, forType: .string)
        case .image:
            if let url = store.imageURL(for: item), let img = NSImage(contentsOf: url) {
                pb.writeObjects([img])
            }
        }
        // Adopt our own change so the poller never re-records (and re-orders) this item.
        lastChangeCount = pb.changeCount
    }
}
